// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkypmutzysgwfyuiggwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJreXBtdXR6eXNnd2Z5dWlnZ3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTQxMjksImV4cCI6MjA3MTE3MDEyOX0.QsNE4d9kJJYnnGRITH4wZxZxwFdRzPHGQVqv_ibGY6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});